#!/bin/sh
### BEGIN INIT INFO
# Provides: wpa_supplicant
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop wpa-supplicant daemon
# Description: WPA supplicant for secure wireless networks
### END INIT INFO

set -e

IFACE="${0##*@}"
DAEMON="/usr/sbin/wpa_supplicant"
NAME="WPA Supplicant daemon"
PIDFILE="/var/run/wpa_supplicant-$IFACE.pid"
DESC="$IFACE"
ARGS="-c /etc/wpa_supplicant/wpa_supplicant-$IFACE.conf -i $IFACE"

case "$1" in
start)
        shift
        echo -n "starting $DESC: $NAME... "
        if ! start-stop-daemon --start --pidfile "$PIDFILE" --make-pidfile \
                --background --exec "$DAEMON" -- $ARGS; then
                echo "failed."
                exit 1
        fi
        echo "done."
        ;;
stop)
        shift
        echo -n "stopping $DESC: $NAME... "
        if ! start-stop-daemon --stop --pidfile "$PIDFILE" >/dev/null; then
                echo "already stopped!"
                exit 0
        fi
        rm -f "$PIDFILE"
        echo "done."
        ;;
restart|reload)
        shift
        echo -n "restarting $DESC: $NAME... "
        $0 stop >/dev/null
        $0 start >/dev/null
        echo "done."
        ;;
status)
        shift
        if ! pid="$(cat "$PIDFILE" 2>/dev/null)"; then
                exit 1
        fi
        echo "$pid"
        ;;
*)
        echo "Usage: ${0##*/} {start|stop|restart|reload|status}" >&2
        exit 1
        ;;
esac
